# Generated by Django 5.0.7 on 2024-08-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_rename_featured_once_toy_was_included_in_home_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='toy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
