# Generated by Django 5.0.7 on 2024-08-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_alter_toy_options_alter_toy_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='toy',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='toy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
